package com.fush.erp.domain.audit

enum class AuditSection {
    SECURITY,
    GOVERNANCE,
    MASTER_DATA,
    SALES_AR,
    PURCHASE_AP,
    ACCOUNTING_TREASURY,
    EXPENSES,
    INVENTORY,
    PRODUCTION,
    HR,
    FIXED_ASSETS,
    PLANNING,
    RISK_CONTROLS,
    BACKUP_RESTORE,
}

data class MandatoryAuditEvent(
    val code: String,
    val section: AuditSection,
    val entityType: String,
    val action: String,
    val requiresReason: Boolean = false,
    val requiresBeforeAfter: Boolean = false,
    val requiresOriginalLink: Boolean = false,
)

/**
 * Phase P0 catalog only.
 *
 * This class defines which sensitive actions MUST be auditable. It intentionally does not
 * write audit rows; actor/session/device/source capture is implemented in P1.
 */
object AuditEventCatalog {
    val mandatory: List<MandatoryAuditEvent> = listOf(
        e("SEC_LOGIN_SUCCESS", AuditSection.SECURITY, "SESSION", "LOGIN_SUCCESS"),
        e("SEC_LOGIN_FAILED", AuditSection.SECURITY, "SESSION", "LOGIN_FAILED", reason = true),
        e("SEC_LOGOUT", AuditSection.SECURITY, "SESSION", "LOGOUT"),
        e("SEC_SESSION_TERMINATED", AuditSection.SECURITY, "SESSION", "TERMINATE", reason = true),
        e("SEC_MFA_FAILED", AuditSection.SECURITY, "MFA", "CHALLENGE_FAILED", reason = true),
        e("SEC_PERMISSION_DENIED", AuditSection.SECURITY, "PERMISSION", "ACCESS_DENIED", reason = true),
        e("SEC_PERMISSION_CHANGED", AuditSection.SECURITY, "PERMISSION", "UPDATE", reason = true, beforeAfter = true),
        e("SEC_ROLE_CHANGED", AuditSection.SECURITY, "ROLE", "UPDATE", reason = true, beforeAfter = true),
        e("SEC_POLICY_CHANGED", AuditSection.SECURITY, "SECURITY_POLICY", "UPDATE", reason = true, beforeAfter = true),
        e("GOV_SUBMIT", AuditSection.GOVERNANCE, "APPROVAL_REQUEST", "SUBMIT"),
        e("GOV_APPROVE", AuditSection.GOVERNANCE, "APPROVAL_REQUEST", "APPROVE", reason = true, originalLink = true),
        e("GOV_REJECT", AuditSection.GOVERNANCE, "APPROVAL_REQUEST", "REJECT", reason = true, originalLink = true),
        e("GOV_REVOKE", AuditSection.GOVERNANCE, "APPROVAL_REQUEST", "REVOKE", reason = true, originalLink = true),
        e("GOV_CHANGE_REQUEST_CREATE", AuditSection.GOVERNANCE, "CHANGE_REQUEST", "CREATE", reason = true),
        e("GOV_CHANGE_REQUEST_DECIDE", AuditSection.GOVERNANCE, "CHANGE_REQUEST", "DECIDE", reason = true, beforeAfter = true, originalLink = true),
        e("MASTER_CREATE", AuditSection.MASTER_DATA, "MASTER", "CREATE"),
        e("MASTER_UPDATE", AuditSection.MASTER_DATA, "MASTER", "UPDATE", reason = true, beforeAfter = true),
        e("MASTER_DEACTIVATE", AuditSection.MASTER_DATA, "MASTER", "DEACTIVATE", reason = true, beforeAfter = true),
        e("MASTER_REACTIVATE", AuditSection.MASTER_DATA, "MASTER", "REACTIVATE", reason = true, beforeAfter = true),
        e("MASTER_PRICE_CHANGED", AuditSection.MASTER_DATA, "PRICE", "UPDATE", reason = true, beforeAfter = true),
        e("MASTER_CREDIT_LIMIT_CHANGED", AuditSection.MASTER_DATA, "CREDIT_LIMIT", "UPDATE", reason = true, beforeAfter = true),
        e("MASTER_UNIT_FACTOR_CHANGED", AuditSection.MASTER_DATA, "UNIT_FACTOR", "UPDATE", reason = true, beforeAfter = true),
        e("SALES_DOCUMENT_CREATE", AuditSection.SALES_AR, "SALES_DOCUMENT", "CREATE"),
        e("SALES_DOCUMENT_POST", AuditSection.SALES_AR, "SALES_DOCUMENT", "POST"),
        e("SALES_DOCUMENT_CANCEL", AuditSection.SALES_AR, "SALES_DOCUMENT", "CANCEL", reason = true, originalLink = true),
        e("SALES_DOCUMENT_REVERSE", AuditSection.SALES_AR, "SALES_DOCUMENT", "REVERSE", reason = true, originalLink = true),
        e("SALES_RETURN_POST", AuditSection.SALES_AR, "SALES_RETURN", "POST", originalLink = true),
        e("SALES_RECEIPT_POST", AuditSection.SALES_AR, "CUSTOMER_RECEIPT", "POST"),
        e("SALES_RECEIPT_REVERSE", AuditSection.SALES_AR, "CUSTOMER_RECEIPT", "REVERSE", reason = true, originalLink = true),
        e("SALES_PRICE_OVERRIDE", AuditSection.SALES_AR, "SALES_PRICE", "OVERRIDE", reason = true, beforeAfter = true),
        e("SALES_DISCOUNT_OVERRIDE", AuditSection.SALES_AR, "SALES_DISCOUNT", "OVERRIDE", reason = true, beforeAfter = true),
        e("PURCHASE_DOCUMENT_CREATE", AuditSection.PURCHASE_AP, "PURCHASE_DOCUMENT", "CREATE"),
        e("PURCHASE_DOCUMENT_POST", AuditSection.PURCHASE_AP, "PURCHASE_DOCUMENT", "POST"),
        e("PURCHASE_DOCUMENT_CANCEL", AuditSection.PURCHASE_AP, "PURCHASE_DOCUMENT", "CANCEL", reason = true, originalLink = true),
        e("PURCHASE_DOCUMENT_REVERSE", AuditSection.PURCHASE_AP, "PURCHASE_DOCUMENT", "REVERSE", reason = true, originalLink = true),
        e("PURCHASE_RETURN_POST", AuditSection.PURCHASE_AP, "PURCHASE_RETURN", "POST", originalLink = true),
        e("SUPPLIER_PAYMENT_POST", AuditSection.PURCHASE_AP, "SUPPLIER_PAYMENT", "POST"),
        e("SUPPLIER_PAYMENT_REVERSE", AuditSection.PURCHASE_AP, "SUPPLIER_PAYMENT", "REVERSE", reason = true, originalLink = true),
        e("PURCHASE_PRICE_OVERRIDE", AuditSection.PURCHASE_AP, "PURCHASE_PRICE", "OVERRIDE", reason = true, beforeAfter = true),
        e("GL_MANUAL_JOURNAL_POST", AuditSection.ACCOUNTING_TREASURY, "JOURNAL_ENTRY", "POST"),
        e("GL_JOURNAL_REVERSE", AuditSection.ACCOUNTING_TREASURY, "JOURNAL_ENTRY", "REVERSE", reason = true, originalLink = true),
        e("GL_JOURNAL_CORRECT", AuditSection.ACCOUNTING_TREASURY, "JOURNAL_ENTRY", "CORRECT", reason = true, beforeAfter = true, originalLink = true),
        e("GL_BACKDATED_POST", AuditSection.ACCOUNTING_TREASURY, "POSTING_DATE", "BACKDATED_POST", reason = true, beforeAfter = true),
        e("GL_PERIOD_CLOSE", AuditSection.ACCOUNTING_TREASURY, "ACCOUNTING_PERIOD", "CLOSE", reason = true),
        e("GL_PERIOD_REOPEN", AuditSection.ACCOUNTING_TREASURY, "ACCOUNTING_PERIOD", "REOPEN", reason = true, beforeAfter = true),
        e("GL_FISCAL_YEAR_CLOSE", AuditSection.ACCOUNTING_TREASURY, "FISCAL_YEAR", "CLOSE", reason = true),
        e("GL_FISCAL_YEAR_REOPEN", AuditSection.ACCOUNTING_TREASURY, "FISCAL_YEAR", "REOPEN", reason = true, beforeAfter = true),
        e("TREASURY_VOUCHER_POST", AuditSection.ACCOUNTING_TREASURY, "TREASURY_VOUCHER", "POST"),
        e("TREASURY_VOUCHER_REVERSE", AuditSection.ACCOUNTING_TREASURY, "TREASURY_VOUCHER", "REVERSE", reason = true, originalLink = true),
        e("TREASURY_CASH_COUNT", AuditSection.ACCOUNTING_TREASURY, "CASH_COUNT", "COUNT"),
        e("TREASURY_CASH_COUNT_RESOLVE", AuditSection.ACCOUNTING_TREASURY, "CASH_COUNT", "RESOLVE", reason = true, beforeAfter = true, originalLink = true),
        e("BANK_STATEMENT_IMPORT", AuditSection.ACCOUNTING_TREASURY, "BANK_STATEMENT", "IMPORT"),
        e("BANK_MATCH", AuditSection.ACCOUNTING_TREASURY, "BANK_RECONCILIATION", "MATCH", originalLink = true),
        e("BANK_UNMATCH", AuditSection.ACCOUNTING_TREASURY, "BANK_RECONCILIATION", "UNMATCH", reason = true, originalLink = true),
        e("BANK_RECONCILE", AuditSection.ACCOUNTING_TREASURY, "BANK_RECONCILIATION", "RECONCILE", reason = true),
        e("FX_REVALUATION_POST", AuditSection.ACCOUNTING_TREASURY, "FX_REVALUATION", "POST"),
        e("FX_REVALUATION_REVERSE", AuditSection.ACCOUNTING_TREASURY, "FX_REVALUATION", "REVERSE", reason = true, originalLink = true),
        e("EXPENSE_CREATE", AuditSection.EXPENSES, "EXPENSE", "CREATE"),
        e("EXPENSE_UPDATE", AuditSection.EXPENSES, "EXPENSE", "UPDATE", reason = true, beforeAfter = true),
        e("EXPENSE_APPROVE", AuditSection.EXPENSES, "EXPENSE", "APPROVE", reason = true, originalLink = true),
        e("EXPENSE_POST", AuditSection.EXPENSES, "EXPENSE", "POST"),
        e("EXPENSE_REVERSE", AuditSection.EXPENSES, "EXPENSE", "REVERSE", reason = true, originalLink = true),
        e("EXPENSE_DIMENSION_CHANGED", AuditSection.EXPENSES, "EXPENSE_DIMENSION", "UPDATE", reason = true, beforeAfter = true),
        e("INV_ADJUSTMENT_POST", AuditSection.INVENTORY, "INVENTORY_ADJUSTMENT", "POST", reason = true, beforeAfter = true),
        e("INV_ADJUSTMENT_REVERSE", AuditSection.INVENTORY, "INVENTORY_ADJUSTMENT", "REVERSE", reason = true, originalLink = true),
        e("INV_COUNT_OPEN", AuditSection.INVENTORY, "INVENTORY_COUNT", "OPEN"),
        e("INV_COUNT_POST", AuditSection.INVENTORY, "INVENTORY_COUNT", "POST", reason = true, beforeAfter = true),
        e("INV_TRANSFER_CREATE", AuditSection.INVENTORY, "WAREHOUSE_TRANSFER", "CREATE"),
        e("INV_TRANSFER_POST", AuditSection.INVENTORY, "WAREHOUSE_TRANSFER", "POST"),
        e("INV_TRANSFER_CANCEL", AuditSection.INVENTORY, "WAREHOUSE_TRANSFER", "CANCEL", reason = true, originalLink = true),
        e("INV_TRANSFER_REVERSE", AuditSection.INVENTORY, "WAREHOUSE_TRANSFER", "REVERSE", reason = true, originalLink = true),
        e("INV_LOT_RECLASSIFY", AuditSection.INVENTORY, "INVENTORY_LOT", "RECLASSIFY", reason = true, beforeAfter = true),
        e("INV_COST_OVERRIDE", AuditSection.INVENTORY, "INVENTORY_COST", "OVERRIDE", reason = true, beforeAfter = true),
        e("PROD_ORDER_CREATE", AuditSection.PRODUCTION, "PRODUCTION_ORDER", "CREATE"),
        e("PROD_ORDER_RELEASE", AuditSection.PRODUCTION, "PRODUCTION_ORDER", "RELEASE"),
        e("PROD_MATERIAL_ISSUE", AuditSection.PRODUCTION, "PRODUCTION_ISSUE", "POST"),
        e("PROD_MATERIAL_RETURN", AuditSection.PRODUCTION, "PRODUCTION_RETURN", "POST", originalLink = true),
        e("PROD_OUTPUT_RECEIPT", AuditSection.PRODUCTION, "PRODUCTION_RECEIPT", "POST"),
        e("PROD_ISSUE_CORRECT", AuditSection.PRODUCTION, "PRODUCTION_ISSUE", "CORRECT", reason = true, beforeAfter = true, originalLink = true),
        e("PROD_RECEIPT_CORRECT", AuditSection.PRODUCTION, "PRODUCTION_RECEIPT", "CORRECT", reason = true, beforeAfter = true, originalLink = true),
        e("PROD_ORDER_CANCEL", AuditSection.PRODUCTION, "PRODUCTION_ORDER", "CANCEL", reason = true, originalLink = true),
        e("PROD_ORDER_DELETE", AuditSection.PRODUCTION, "PRODUCTION_ORDER", "DELETE", reason = true, beforeAfter = true),
        e("HR_EMPLOYEE_CREATE", AuditSection.HR, "EMPLOYEE", "CREATE"),
        e("HR_EMPLOYEE_UPDATE", AuditSection.HR, "EMPLOYEE", "UPDATE", reason = true, beforeAfter = true),
        e("HR_EMPLOYEE_STATUS", AuditSection.HR, "EMPLOYEE", "STATUS_CHANGE", reason = true, beforeAfter = true),
        e("HR_COMPENSATION_CHANGED", AuditSection.HR, "EMPLOYEE_COMPENSATION", "UPDATE", reason = true, beforeAfter = true),
        e("HR_PAYROLL_POST", AuditSection.HR, "PAYROLL", "POST"),
        e("HR_PAYROLL_REVERSE", AuditSection.HR, "PAYROLL", "REVERSE", reason = true, originalLink = true),
        e("ASSET_CREATE", AuditSection.FIXED_ASSETS, "FIXED_ASSET", "CREATE"),
        e("ASSET_UPDATE", AuditSection.FIXED_ASSETS, "FIXED_ASSET", "UPDATE", reason = true, beforeAfter = true),
        e("ASSET_CAPITALIZE", AuditSection.FIXED_ASSETS, "FIXED_ASSET", "CAPITALIZE"),
        e("ASSET_DEPRECIATION_POST", AuditSection.FIXED_ASSETS, "DEPRECIATION", "POST"),
        e("ASSET_DEPRECIATION_REVERSE", AuditSection.FIXED_ASSETS, "DEPRECIATION", "REVERSE", reason = true, originalLink = true),
        e("ASSET_DISPOSE", AuditSection.FIXED_ASSETS, "FIXED_ASSET", "DISPOSE", reason = true, beforeAfter = true),
        e("PLAN_CREATE", AuditSection.PLANNING, "PLAN", "CREATE"),
        e("PLAN_UPDATE", AuditSection.PLANNING, "PLAN", "UPDATE", reason = true, beforeAfter = true),
        e("PLAN_APPROVE", AuditSection.PLANNING, "PLAN", "APPROVE", reason = true, originalLink = true),
        e("PLAN_REOPEN", AuditSection.PLANNING, "PLAN", "REOPEN", reason = true, beforeAfter = true, originalLink = true),
        e("RISK_CREATE", AuditSection.RISK_CONTROLS, "RISK", "CREATE"),
        e("RISK_REVIEW", AuditSection.RISK_CONTROLS, "RISK", "REVIEW", reason = true, beforeAfter = true),
        e("CONTROL_CREATE", AuditSection.RISK_CONTROLS, "CONTROL", "CREATE"),
        e("CONTROL_TEST", AuditSection.RISK_CONTROLS, "CONTROL", "TEST", reason = true),
        e("CONTROL_EXCEPTION_CREATE", AuditSection.RISK_CONTROLS, "CONTROL_EXCEPTION", "CREATE", reason = true),
        e("CONTROL_EXCEPTION_CLOSE", AuditSection.RISK_CONTROLS, "CONTROL_EXCEPTION", "CLOSE", reason = true, beforeAfter = true, originalLink = true),
        e("BACKUP_CREATE", AuditSection.BACKUP_RESTORE, "BACKUP", "CREATE"),
        e("BACKUP_EXPORT", AuditSection.BACKUP_RESTORE, "BACKUP", "EXPORT"),
        e("RESTORE_START", AuditSection.BACKUP_RESTORE, "RESTORE", "START", reason = true),
        e("RESTORE_SUCCESS", AuditSection.BACKUP_RESTORE, "RESTORE", "SUCCESS", reason = true, originalLink = true),
        e("RESTORE_FAILED", AuditSection.BACKUP_RESTORE, "RESTORE", "FAILED", reason = true, originalLink = true),
    )

    val bySection: Map<AuditSection, List<MandatoryAuditEvent>> = mandatory.groupBy { it.section }

    private fun e(
        code: String,
        section: AuditSection,
        entityType: String,
        action: String,
        reason: Boolean = false,
        beforeAfter: Boolean = false,
        originalLink: Boolean = false,
    ) = MandatoryAuditEvent(code, section, entityType, action, reason, beforeAfter, originalLink)
}
